num1=int(input('enter a number:'))
num2=int(input('enter a number:'))
num3=int(input('enter a number:'))
addition=(num1+num2)
print("the sum of num1 and num2 is :",addition)
subtraction=(num1-num2)
print("The difference when num2 is subtracted from num1 is :",subtraction)
multiplication=(num1*num2)
print("The product of num1 and num2 is:",multiplication)
division=(num1/num2,num2!=0)
print("The quoient when num1 is divided by numi2s :",division)
modulus=(num1%num2)
print("The reminder when num1 is divided by num2is :",modulus)
combination=((addition*num3)/2)
print("The result of (nur1+num2)*num3/2 is :",combination)
